### ISSUE TITLE
error happens during the "Run FEP" step in the "Farnesoid X receptor tutorial"

### ISSUE THREAD

**Issue by yx0516** [luancarvalhomartins/PyAutoFEP#52] opened 2022-06-10 07:25 UTC
After the "Run FEP" step, the file "tutorial.tgz" has been created. However in the "nohup.out" file, the content are as follows:

```
tar: */water/md/rerun/*.pkl: Cannot stat: No such file or directory
tar: */water/md/rerun/*.xvg: Cannot stat: No such file or directory
tar: */water/md/rerun/*.edr: Cannot stat: No such file or directory
tar: */protein/md/rerun/*.pkl: Cannot stat: No such file or directory
tar: */protein/md/rerun/*.xvg: Cannot stat: No such file or directory
tar: */protein/md/rerun/*.edr: Cannot stat: No such file or directory
tar: */water/md/lambda*/lambda_pbcfit.xtc: Cannot stat: No such file or directory
tar: */water/md/lambda*/lambda.log: Cannot stat: No such file or directory
tar: */water/md/lambda*/lambda.edr: Cannot stat: No such file or directory
tar: */protein/md/lambda*/lambda_pbcfit.xtc: Cannot stat: No such file or directory
tar: */protein/md/lambda*/lambda.log: Cannot stat: No such file or directory
tar: */protein/md/lambda*/lambda.edr: Cannot stat: No such file or directory
tar: */water/md/lambda*/analysis.log: Cannot stat: No such file or directory
tar: */protein/md/lambda*/analysis.log: Cannot stat: No such file or directory
tar: */water/md/analysis/*.xvg: Cannot stat: No such file or directory
tar: */protein/md/analysis/*.xvg: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
```

And  when i run the "analysis step", error happens,

```
[ERROR] Could not find unk_matrix.pkl file in tutorial/FXR_12-FXR_74/water/md/rerun to read temperature from. Also, could not s temperature from MD log in tutorial/FXR_12-FXR_74/water/md/rerun/../lambda0/lambda.log. Set temperature argument or config on. Analysis for this system will not be run.
=================== STACK INFO ===================
  File "analyze_results.py", line 1511, in <module>
    verbosity=arguments.verbose)
  File "analyze_results.py", line 1173, in collect_from_xvg
    msg_verbosity=os_util.verbosity_level.error, current_verbosity=verbosity)
  File "/data/user/yanx/workdir/repo/PyAutoFEP/os_util.py", line 292, in local_print
    formatted_string += '\n{:=^50}\n{}{:=^50}'.format(' STACK INFO ', ''.join(traceback.format_stack()),
=================== STACK INFO ===================
```

I think the 'rerun error' happens, there are no files in any 'rerun' fold.  How should i do to fix this?
We would appreciate it if you could check with this when you have time.
@luancarvalhomartins 

---
Edit: Formatted code output to improved readability - @luancarvalhomartins 2022.06.10

**Comment by yx0516** [comment] 2022-06-13 05:49
I have checked the */protein/md/lambda*/ directories, the output are as follows,

drwxrwxr-x  2 yanx yanx   83 Jun 10 13:38 ./
drwxrwxr-x 16 yanx yanx  277 Jun  9 10:33 ../
-rw-rw-r--  1 yanx yanx 2.0M Jun  9 11:59 lambda_nocont.tpr
-rw-rw-r--  1 yanx yanx 2.0M Jun  9 11:59 lambda.tpr
-rw-rw-r--  1 yanx yanx    0 Jun  9 10:33 plumed.dat

 the ouput of all the lambda* directories are similar to the above

**Comment by luancarvalhomartins** [comment] 2022-06-15 16:03
Yep, the run step did not run. Take a look at the `feprun_HHMMSS_DDMMYYY.log` files in `protein/md`. As I mentioned, often the problem is using `gmx` as the `gmx_bin_run`:

> Note: the most common problem is not setting `gmx_bin_run` to a MPI-capable binary. Until before [190bef6](https://github.com/luancarvalhomartins/PyAutoFEP/commit/190bef691195402a4253fe749a77f2aaeea6e620) the default GROMACS binary was `gmx`, while after [190bef6](https://github.com/luancarvalhomartins/PyAutoFEP/commit/190bef691195402a4253fe749a77f2aaeea6e620) the default is `gmx_mpi`.

**Comment by Glinttsd** [comment] 2022-07-13 13:05
Hi, I also encountered this problem. I can't find `gmx_mpi` binary in the `gromacs/bin` folder, so I can't change `gmx` to `gmx_mpi`. BTW, I am using the 48341e4 version.

**Comment by luancarvalhomartins** [comment] 2022-07-13 13:11
@Glinttsd You must compile GROMACS with MPI support, which is required for using `gmx_mpi mdrun -multirun`. Please, take a look at the relevant [GROMACS manual](https://manual.gromacs.org/current/install-guide/index.html#mpi-support) section.

**Comment by Glinttsd** [comment] 2022-07-13 13:15
> @Glinttsd You must compile GROMACS with MPI support, which is required for using `gmx_mpi mdrun -multirun`. Please, take a look at the relevant [GROMACS manual](https://manual.gromacs.org/current/install-guide/index.html#mpi-support) section.

Thank you for your advice, currently I dont want to use the MPI support, can I choose to use single machine with multiple cores?

**Comment by luancarvalhomartins** [comment] 2022-07-13 13:21
You seem to be confused about what MPI support means. You can use a single node, even a single core, and run multiple parallel `gmx_mpi` instances with MPI. Running in a single node is actually the default. However, by design, running multiple simulations using `-multirun` requires MPI-support.

So yes, you can use a single machine with multiple cores, but no, you cannot do that without MPI.

**Comment by Glinttsd** [comment] 2022-07-14 11:34
Hi, I've additionally compiled `gmx_mpi` binary, which is located in `/usr/local/gromacs`. But I still encountered the same problem as described before (after the `bash runall.sh` command).

 I furthur tried to run `bash runall_FXR_12-FXR_74_water.sh` alone, but this error occured:
 
`runall_FXR_12-FXR_74_water.sh: line 7: FXR_12-FXR_74/water/lambda0/min01/min01_grompp.log: No such file or director`. 

I confirmed that the `min01_grompp.log` does not exist in the corresponding directory. Did I miss something?

**Comment by Glinttsd** [comment] 2022-07-14 11:42
I also notice that this command `echo "$(date): Starting equilibration in FXR_12-FXR_74 water at $(hostname)"` in `runall_FXR_12-FXR_74_water.sh` should print something in the terminal, but I found nothing when I run `bash runall.sh` except the final error messages as described before.

**Comment by luancarvalhomartins** [comment] 2022-07-14 15:16
The following error

> `runall_FXR_12-FXR_74_water.sh: line 7: FXR_12-FXR_74/water/lambda0/min01/min01_grompp.log: No such file or director`.

Suggests the runscript didn't find the directory to create `min01_grompp.log` into. Make sure you are running `runall.sh` from the correct location. In order to run `bash runall_FXR_12-FXR_74_water.sh` directly, you have to do that from the parent directory, so using:

`bash FXR_12-FXR_74/runall_FXR_12-FXR_74_water.sh`

Also, make sure your `gmx_mpi` location matches the ones in `FXR_12-FXR_74/runall_FXR_12-FXR_74_water.sh` and other `runall_*.sh` scripts.

**Comment by Glinttsd** [comment] 2022-07-17 14:37
> 

Hi, I further found out that the script `tutorial/FXR_12-FXR_74/runall_FXR_12-FXR_74_water.sh` works fine, 
but `tutorial/FXR_12-FXR_74/runall_FXR_12-FXR_74_protein.sh` does not, which is due to the error occured in line 24 of `tutorial/FXR_12-FXR_74/runall_FXR_12-FXR_74_protein.sh`. 

Line 24 failed because there are **4** warnings, but only **3** are allowed by `--maxwarn 3` in line 24. I changed every `--maxwarn 3` into `--maxwarn 4` and I could run `tutorial/FXR_12-FXR_74/runall_FXR_12-FXR_74_protein.sh` without errors. 

Now I am waiting for the process to finish and see what I can get.

**Comment by Glinttsd** [comment] 2022-07-18 15:31
> The following error
> 
> > `runall_FXR_12-FXR_74_water.sh: line 7: FXR_12-FXR_74/water/lambda0/min01/min01_grompp.log: No such file or director`.
> 
> Suggests the runscript didn't find the directory to create `min01_grompp.log` into. Make sure you are running `runall.sh` from the correct location. In order to run `bash runall_FXR_12-FXR_74_water.sh` directly, you have to do that from the parent directory, so using:
> 
> `bash FXR_12-FXR_74/runall_FXR_12-FXR_74_water.sh`
> 
> Also, make sure your `gmx_mpi` location matches the ones in `FXR_12-FXR_74/runall_FXR_12-FXR_74_water.sh` and other `runall_*.sh` scripts.

Hi, I encountered multiple `environment: rerun/rerun_struct_coord.out: No such file or directory` error at `runall_FXR_12-FXR_74_protein.sh` line 370, 
`parallel --jobs=1 --joblog analysis_joblog_$(date "+%H%M%S_%d%m%Y").log 'cd {//} && [ ! -f "{.}_pbcfit.xtc" ] && fn' ::: ${trajectory_files}
`
Is there anything that I missed?

**Comment by luancarvalhomartins** [comment] 2022-07-24 23:05
The `rerun/rerun_struct*_coord*.out` files are created when running `gmx mdrun -rerun`. The error may suggest that the destination folder ` rerun` was not found. Maybe you are running `runall_FXR_12-FXR_74_protein.sh` manually. If so, make sure you run it on the same folder `runall.sh` is located (which is named based on the `perturbation_dir` argument or option).

**Comment by luancarvalhomartins** [comment] 2022-08-02 13:17
I filled a issue (#59) to track the `environment: rerun/rerun_struct_coord.out: No such file or directory` error. Closing this one as the first part has been solved.

**Closed by luancarvalhomartins** 2022-08-02 13:17 UTC
Labels: not_a_bug, question
