### ISSUE TITLE
analyze_results.py:578: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.   processed_u_nk = processed_u_nk.append(each_structure_block)

### ISSUE THREAD

**Issue by xy21hb** [luancarvalhomartins/PyAutoFEP#106] opened 2023-08-01 04:33 UTC
Dear all,

I once read this issue in this list, but could not find it any more. Not sure if it is due to the same problem, i.e. pandas deprecation.

**Comment by luancarvalhomartins** [comment] 2023-08-01 23:13
Yep, that's #88

**Comment by luancarvalhomartins** [comment] 2023-08-01 23:13
Duplicate of #88

**Closed by luancarvalhomartins** 2023-08-01 23:13 UTC
Labels: duplicate
