### ISSUE TITLE
mpirun vs nve dilemma

### ISSUE THREAD

**Issue by xy21hb** [luancarvalhomartins/PyAutoFEP#98] opened 2023-07-12 07:47 UTC
Dear all,

I am using Gromacs 2019.6 on a single node to run Tutorial, I set "gmx_bin_run=mpirun gmx_mpi" in step2.ini

when running runall.sh on Page 5, it gives the error below, i.e. it cannot pass NVE step, 

![image](https://github.com/luancarvalhomartins/PyAutoFEP/assets/14272986/3fe9c07a-59b9-420b-ac5e-ba9d4e07ec4e)

However, if I set "gmx_bin_run=mpirun -np 24 gmx_mpi" in step2.ini, it can go till Rerun step for multiple directory rerunning,
but fails with error "Mpirun does not support recursive call", ....

I wonder how I could set this gmx_bin_run, if it does not specify "-np #", it would lead to errors for domain decomposition and perhaps occupy all the ranks on a single node.

**Comment by luancarvalhomartins** [comment] 2023-07-14 18:26
Duplicate of #97

**Closed by luancarvalhomartins** 2023-07-14 18:26 UTC
Labels: duplicate
